# Comprehensive Auto-Generated WHO ATC Database for Taiwan NHI Regulated Drugs
WHO_ATC_DATABASE = {
    "H05AA02": {"atc7": "H05AA02", "atc5": "H05AA", "en": "Teriparatide", "tc": "特立帕肽 (副甲狀腺素)", "class_en": "Parathyroid hormones and analogues", "class_tc": "副甲狀腺素及類似劑 / 骨質疏鬆症治療藥物", "brand": "Forteo (骨復力 / 復骨嚴 / Forteo)"},
    "L01FF02": {"atc7": "L01FF02", "atc5": "L01FF", "en": "Pembrolizumab", "tc": "派姆單抗", "class_en": "PD-1/PD-L1 Inhibitors", "class_tc": "免疫檢查點抑制劑 (PD-1/PD-L1)", "brand": "Keytruda (吉利得)"},
    "L01FF01": {"atc7": "L01FF01", "atc5": "L01FF", "en": "Nivolumab", "tc": "納武單抗", "class_en": "PD-1/PD-L1 Inhibitors", "class_tc": "免疫檢查點抑制劑 (PD-1/PD-L1)", "brand": "Opdivo (保疾伏)"},
    "L01FF05": {"atc7": "L01FF05", "atc5": "L01FF", "en": "Atezolizumab", "tc": "阿特珠單抗", "class_en": "PD-1/PD-L1 Inhibitors", "class_tc": "免疫檢查點抑制劑 (PD-1/PD-L1)", "brand": "Tecentriq (癌自禦)"},
    "L01FF06": {"atc7": "L01FF06", "atc5": "L01FF", "en": "Durvalumab", "tc": "度伐利尤單抗", "class_en": "PD-1/PD-L1 Inhibitors", "class_tc": "免疫檢查點抑制劑 (PD-1/PD-L1)", "brand": "Imfinzi (英飛凡)"},
    "L01EX29": {"atc7": "L01EX29", "atc5": "L01EX", "en": "Fruquintinib", "tc": "芙奎替尼", "class_en": "Protein Kinase Inhibitors", "class_tc": "蛋白激酶抑制劑 (VEGFR/TKI)", "brand": "Fruzaqla (愛優特)"},
    "L01EX05": {"atc7": "L01EX05", "atc5": "L01EX", "en": "Regorafenib", "tc": "瑞戈非尼", "class_en": "Protein Kinase Inhibitors", "class_tc": "蛋白激酶抑制劑 (VEGFR/TKI)", "brand": "Stivarga (癌瑞格)"},
    "L01EX08": {"atc7": "L01EX08", "atc5": "L01EX", "en": "Lenvatinib", "tc": "樂伐替尼", "class_en": "Protein Kinase Inhibitors", "class_tc": "蛋白激酶抑制劑 (VEGFR/TKI)", "brand": "Lenvima (樂衛瑪)"},
    "L01EB01": {"atc7": "L01EB01", "atc5": "L01EB", "en": "Gefitinib", "tc": "吉非替尼", "class_en": "EGFR Kinase Inhibitors", "class_tc": "EGFR 標靶藥物", "brand": "Iressa (艾瑞莎)"},
    "L01EB02": {"atc7": "L01EB02", "atc5": "L01EB", "en": "Erlotinib", "tc": "厄洛替尼", "class_en": "EGFR Kinase Inhibitors", "class_tc": "EGFR 標靶藥物", "brand": "Tarceva (得舒緩)"},
    "L01EB03": {"atc7": "L01EB03", "atc5": "L01EB", "en": "Afatinib", "tc": "阿法替尼", "class_en": "EGFR Kinase Inhibitors", "class_tc": "EGFR 標靶藥物", "brand": "Giotrif (妥複克)"},
    "L01EB04": {"atc7": "L01EB04", "atc5": "L01EB", "en": "Osimertinib", "tc": "奧希替尼", "class_en": "EGFR Kinase Inhibitors", "class_tc": "EGFR 標靶藥物", "brand": "Tagrisso (泰格莎)"},
    "L01EF01": {"atc7": "L01EF01", "atc5": "L01EF", "en": "Palbociclib", "tc": "帕博西尼", "class_en": "CDK4/6 Inhibitors", "class_tc": "CDK4/6 抑制劑", "brand": "Ibrance (愛乳適)"},
    "A10BK03": {"atc7": "A10BK03", "atc5": "A10BK", "en": "Empagliflozin", "tc": "恩格列淨", "class_en": "SGLT2 Inhibitors", "class_tc": "SGLT2 抑制劑 (排糖藥)", "brand": "Jardiance (恩智平)"},
    "A10BK01": {"atc7": "A10BK01", "atc5": "A10BK", "en": "Dapagliflozin", "tc": "達格列淨", "class_en": "SGLT2 Inhibitors", "class_tc": "SGLT2 抑制劑 (排糖藥)", "brand": "Forxiga (福可適)"},
    "A10BJ06": {"atc7": "A10BJ06", "atc5": "A10BJ", "en": "Semaglutide", "tc": "司美格魯肽", "class_en": "GLP-1 Receptor Agonists", "class_tc": "GLP-1 受體促效劑 (瘦瘦針)", "brand": "Ozempic (胰島讚)"},
    "C10AA05": {"atc7": "C10AA05", "atc5": "C10AA", "en": "Atorvastatin", "tc": "阿托伐他汀", "class_en": "Statins", "class_tc": "Statins 降血脂藥", "brand": "Lipitor (立普妥)"},
    "C10AA07": {"atc7": "C10AA07", "atc5": "C10AA", "en": "Rosuvastatin", "tc": "瑞舒伐他汀", "class_en": "Statins", "class_tc": "Statins 降血脂藥", "brand": "Crestor (冠脂妥)"},
    "B01AF01": {"atc7": "B01AF01", "atc5": "B01AF", "en": "Rivaroxaban", "tc": "利伐沙班", "class_en": "DOACs", "class_tc": "DOACs 新型口服抗凝血劑", "brand": "Xarelto (拜瑞妥)"},
    "L04AB04": {"atc7": "L04AB04", "atc5": "L04AB", "en": "Adalimumab", "tc": "阿達木單抗", "class_en": "TNF-alpha Inhibitors", "class_tc": "抗腫瘤壞死因子 (TNF-alpha 生物製劑)", "brand": "Humira (復邁)"},
    "L04AB01": {"atc7": "L04AB01", "atc5": "L04AB", "en": "Etanercept", "tc": "恩博", "class_en": "TNF-alpha Inhibitors", "class_tc": "抗腫瘤壞死因子 (TNF-alpha 生物製劑)", "brand": "Enbrel (恩博)"},
    "L04AC05": {"atc7": "L04AC05", "atc5": "L04AC", "en": "Ustekinumab", "tc": "烏司他單抗", "class_en": "Interleukin Inhibitors", "class_tc": "白血球介素抑制劑 (IL-12/23)", "brand": "Stelara (喜達諾)"},
    "L04AC12": {"atc7": "L04AC12", "atc5": "L04AC", "en": "Secukinumab", "tc": "蘇金單抗", "class_en": "Interleukin Inhibitors", "class_tc": "白血球介素抑制劑 (IL-17A)", "brand": "Cosentyx (可善挺)"},
    "D11AH05": {"atc7": "D11AH05", "atc5": "D11AH", "en": "Dupilumab", "tc": "杜匹魯單抗", "class_en": "Interleukin Inhibitors", "class_tc": "異位性皮膚炎生物製劑", "brand": "Dupixent (杜避炎)"},
    "L04AA29": {"atc7": "L04AA29", "atc5": "L04AA", "en": "Tofacitinib", "tc": "托法替尼", "class_en": "JAK Inhibitors", "class_tc": "JAK 激酶抑制劑", "brand": "Xeljanz (捷抑妥)"},
    "J05AF05": {"atc7": "J05AF05", "atc5": "J05AF", "en": "Entecavir", "tc": "恩替卡韋", "class_en": "Antivirals", "class_tc": "B型肝炎口服抗病毒藥物", "brand": "Baraclude (貝樂克)"},
    "J05AF13": {"atc7": "J05AF13", "atc5": "J05AF", "en": "Tenofovir alafenamide", "tc": "替諾福韋丙酚酚胺", "class_en": "Antivirals", "class_tc": "B型肝炎口服抗病毒藥物", "brand": "Vemlidy (韋立得)"}
}
